### ISSUE TITLE
[EPIC]Implementar banco de dados 

### ISSUE THREAD

**Issue by lilialnas** [ThierryMatheus/ProjetoPilotoPEP2#1]
Criar um banco de dados para armazenar dados cadastrais e as denúncias no sistema.

- [x] Criar Modelo Conceitual
- [x] Criar Modelo Lógico
- [x] Criar Modelo físico
