### ISSUE TITLE
[EPIC] Cadastro de usuário e autenticação

### ISSUE THREAD

**Issue by lilialnas** [ThierryMatheus/ProjetoPilotoPEP2#2]
- [x] Cadastro de usuário
(definir quais dados serão solicitados)
- [ ]  Teremos mecanismo de validação de cadastro?
- [ ] Tela de autenticação do sistema (Entrar/Cadastrar) Nunca usar a palavra "login". Esqueceu a senha? Primeiro acesso?
- [ ]  Definir a arquitetura de autenticação no sistema.
### Façam issues pequenas para diminuir o risco da não entrega e também que todos tenham demanda para trabalhar.
_Por favor, quebrem ao máximo uma issue. Exemplos: Criar model do usuário. Criar model da denúncia._

**Comment by huandersonlima** [comment]
Cadastro de usuário feito na issue #11
